
######################
# Sample Definitions #
######################

clip_samples:
  RBFOX_rep1: {r1: "ENCFF172GUS", r2: "ENCFF647KDW"}
  RBFOX_rep2: {r1: "ENCFF591SSP", r2: "ENCFF289OFA"}

control_samples:
  Control_rep1:  {r1: "ENCFF264UQQ", r2: "ENCFF648TWD"}

###############
# Directories #
###############

# input directory
sample_data_dir: "/scratch/bi03/heylf/eCLIP/RBFOX2"

# output directories
renaming_outdir:  "renaming"
fastqc_beg_outdir:  "fastqc_beginning"
fastqc_adapt_outdir:  "fastqc_after_trimming"
cutadapt_outdir:  "cutadapt"
trim_galore_outdir: "trim_galore"
remove_tail_outdir: "remove_tail"
mapping_outdir: "mapping"
mapping_quality_outdir: "mapping_quality"
preprocessing_for_umi_outdir: "preprocessing_for_umi"
deduplication_outdir: "deduplication"
fastqc_dedup_outdir:  "fastqc_after_deduplication"
coverage_outdir:  "coverage"
peakcalling_outdir:  "peakcalling"
post_processing_outdir: "post_processing"
motif_detection_outdir: "motif_detection"
motif_search_outdir: "motif_search"

# tool directories
bctools: "scripts"
rcas: "scripts"
extract_genomic_dna: "scripts"
dreme: "/scratch/bi01/heylf/miniconda3/bin"
